### PR TITLE
https://jira.desk.technology/browse/MSDKI-39

### PR DESCRIPTION
**Pull request by nartiles**
@eldark88 please review

### CODE REVIEW

**Comment by eldark88** [comment]
@nartiles first pass done

**Comment by nartiles** [comment]
@eldark88 please review. Note that the changes relating to networkActivityDidEnd were for an unrelated bug (crash).

**Comment by eldark88** [comment]
@nartiles looks good, added couple small comments

**Comment by nartiles** [comment]
@eldark88 see last commit.

**Comment by eldark88** [comment]
@nartiles looks good :shipit:

**Pull request merged**
